### ISSUE TITLE
Invoke multiple storage.stores in parallel

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/contile#338] opened 2021-12-29 21:01 UTC
We could probably `join!` the potentially multiple calls to `StorageImage::store` to invoke them all in parallel. This may not be a huge win since there's currently a limit of 2 tiles and some of the work is CPU based (image hashing), but there's also at least one and potentially two http requests per store call.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1499)
┆epic: Contile efficiency enhancements

**Comment by jrconlin** [comment] 2022-01-04 19:29
Duplicate of #232

**Closed by jrconlin** 2022-01-04 19:29 UTC
Labels: enhancement
