### ISSUE TITLE
Do not report image upload rate exceeded as a sentry error

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/contile#301] opened 2021-10-11 23:51 UTC
Currently, there can be instances where [more than one node may try to upload a given image](https://sentry.prod.mozaws.net/operations/contile/issues/13683606/?environment=prod) (even with the current locks in place). This should be alleviated by the [shared cache](https://github.com/mozilla-services/contile/issues/251), but in any case, we don't need to report the inactionable error to sentry.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DISCO-1305)

**Comment by data-sync-user** [comment] 2021-10-15 22:17
➤ Philip Jenvey commented:

Marked as low because we don’t generate many of these, only about 100 so far for maybe 3-5? image uploads total and a number of them were caused by sporadic DNS lookup failures.

**Closed** 2024-06-11 17:09 UTC
Labels: good-first-issue
