### ISSUE TITLE
Render actual JSON error responses

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/contile#340] opened 2021-12-29 21:02 UTC
To aid in debugging we should return actual JSON error responses -- we currently return a payload of the error's status code, inherited from syncstorage-rs.

Technically this is json as we're sending `Content-Type: application/json` and a number, but this should be more along the lines of our other services's, e.g. megaphone's:

```
$ curl https://dev.megaphone.nonprod.cloudops.mozgcp.net/nonexistant
{"code":404,"errno":123,"error":"Not Found"}
```

Let's double check this won't affect the client but I believe it currently only cares about the http status code.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1497)
┆epic: Contile efficiency enhancements

**Comment by jrconlin** [comment] 2022-01-04 19:33
Duplicate of #177

**Closed by jrconlin** 2022-01-04 19:33 UTC
Labels: enhancement
