### ISSUE TITLE
3.5.2 Create an internal service endpoint to emergency purge the cache

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/contile#40] opened 2021-04-09 18:56 UTC
This entry point should force purge all records from the cache.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-205)
┆Epic: Contile Shared Cache

**Comment by data-sync-user** [comment] 2021-09-28 22:30
➤ Philip Jenvey commented:

Duplicate of https://mozilla-hub.atlassian.net/browse/CONSVC-207, closing

**Closed by data-sync-user** 2021-09-28 22:30 UTC
Labels: 5
