### ISSUE TITLE
Rate limit calls to adM in downtime conditions

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/contile#341] opened 2021-12-29 21:02 UTC
When there's issues with the adM tile API service (e.g. timeouts), contile can end up queuing a large (too many) number of requests to adM. We should restrict the number of total connections initiated, likely 503ing to clients when there's too many.

**Acceptance Criteria:**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1496)
┆epic: Contile efficiency enhancements

**Comment by jrconlin** [comment] 2022-01-04 19:32
Duplicate of #220

**Closed by jrconlin** 2022-01-04 19:32 UTC
Labels: enhancement
